### ISSUE TITLE
Improve Card Styling with Dynamic Colors

### ISSUE THREAD

**Issue by JollyJolli** [narainkarthikv/contribution-cards#22]
**Description:**

Currently, the `users.css` file applies manual styling to each card, resulting in a static and cumbersome approach. As the project grows, applying individual styles to each card will become impractical. It would be beneficial to introduce a script that dynamically assigns unique colors to each card. This would allow each card to have a distinct color every time the page is refreshed and scale more efficiently as the project expands.

**Proposed Solution:**

- Create a script that automatically generates and assigns a unique color to each card.
- Ensure that the color is applied consistently across page reloads to maintain visual appeal.
- Optionally, provide a range of color schemes or patterns to choose from for added customization.
- Implement the solution in a way that scales easily, eliminating the need for manual styling for each card as the project grows.

**Benefits:**

- Enhances visual differentiation between cards.
- Improves user experience by providing a dynamic and engaging interface.
- Scales effectively with project growth by automating card styling.
- Reduces the need for manual CSS adjustments for card styling.

**Comment by narainkarthikv** [comment]
@JollyJolli This feature seems promising, but please ensure the color assigned to a card remains consistent even after a reload. This will help prevent potential issues, especially when there are many cards and frequent reloads.

**Comment by JollyJolli** [comment]
Ready! I all ready open a pull request with this feature (#23).
